# Generated by Django 2.2.10 on 2021-04-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20210414_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='manage',
        ),
    ]
